mpi:
  - mpich
  - openmpi

moose_petsc:
  - moose-petsc 3.22.1.193.g72c1e49ee3d mpich_0
  - moose-petsc 3.22.1.193.g72c1e49ee3d openmpi_0

moose_libmesh_vtk:
  - moose-libmesh-vtk 9.3.0 mpich_4
  - moose-libmesh-vtk 9.3.0 openmpi_4

zip_keys:
  - mpi
  - moose_petsc
  - moose_libmesh_vtk

#### Darwin SDK SYSROOT
CONDA_BUILD_SYSROOT:                                        # [osx]
  - /opt/MacOSX11.3.sdk                                     # [osx]

macos_min_version:                                          # [osx]
  - 11.3                                                    # [osx]

macos_machine:                                              # [osx]
  - x86_64-apple-darwin13.4.0                               # [not arm64 and osx]
  - arm64-apple-darwin20.0.0                                # [arm64]

MACOSX_DEPLOYMENT_TARGET:                                   # [osx]
  - 11.3                                                    # [osx]
